---
output: 
    bookdown::pdf_document2:
        toc: no
        includes:
            in_header: assets/csl-bib-sty/styles.sty
        df_print: kable
        number_sections: true
geometry: "left=3.5cm,right=2.5cm,top=2.5cm,bottom=2.5cm"
mainfont: Times New Roman
fontsize: 12pt
csl: assets/csl-bib-sty/apa.csl
bibliography: [assets/csl-bib-sty/references_inv_books.bib, 
               assets/csl-bib-sty/references_inv_manuals.bib,
               assets/csl-bib-sty/references_inv_web.bib]
nocite: '@*'
---

<!-- Configuración CHUNKS -->
```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      fig.align='center',
                      out.height='60%',
                      out.width='100%')

knitr::opts_knit$set(root.dir = getwd())

options(scipen=999)

```

\includepdf[pages=-]{RECURSOS-INVESTIGACION/CARATULA/CARATULA}

\clearpage
\pagenumbering{roman}

```{=latex}
\startcontents[mainsections]
```
<!-- PREAMBULO -->
\newpage
```{r, child="RECURSOS-INVESTIGACION/000-PREAMBULO/000-PREAMBULO.Rmd"}

```


```{=latex}
\newpage
\printcontents[mainsections]{}{1}{\section*{INDICE CAPITULAR}}
```

\newpage
\listoffigures
\newpage
\listoftables

\clearpage
\pagenumbering{arabic}

<!-- PREAMBULO -->
\newpage
```{r, child="RECURSOS-INVESTIGACION/000-PREAMBULO/000-INTRODUCCION.Rmd"}
```

<!-- PERFIL DEL PROYECTO -->
\newpage
```{r, child="RECURSOS-INVESTIGACION/001-PERFIL-DEL-PROYECTO/001-PERFIL-DEL-PROYECTO.Rmd"}
```

<!-- MARCO TEÓRICO -->
\newpage
```{r, child="RECURSOS-INVESTIGACION/003-MARCO-TEORICO/003-MARCO-TEORICO.Rmd"}
```

<!-- DIAGNOSTICO SISTEMA FINANCIERO -->
\newpage
```{r, child="RECURSOS-INVESTIGACION/004-DIAGNOSTICO-SISTEMA-FINANCIERO/004-DIAGNOSTICO-SISTEMA-FINANCIERO.Rmd"}
```

<!-- DETERMINACION REDES NEURONALES-PRONOSTICOS -->
\newpage
```{r, child="RECURSOS-INVESTIGACION/005-DETERMINACION-REDES-NEURONALES-PRONOSTICOS/005-DETERMINACION-REDES-NEURONALES-PRONOSTICOS.Rmd"}
```

<!-- CONCLUSIONES Y RECOMENDACIONES -->
\newpage
```{r, child="RECURSOS-INVESTIGACION/006-CONCLUSIONES-RECOMENDACIONES/006-CONCLUSIONES-RECOMENDACIONES.Rmd"}
```

<!-- REFERENCIAS BIBLIOGRAFICAS -->
\newpage
```{r, child="RECURSOS-INVESTIGACION/009-REFERENCIAS-BIBLIOGRAFICAS/009-REFERENCIAS-BIBLIOGRAFICAS.Rmd"}
```

<!-- ANEXOS TITULO-->
\newpage
\phantomsection\addcontentsline{toc}{footerms}{ANEXOS}

```{=latex}
\stopcontents[mainsections]
```


<!-- ANEXOS CONTENIDO-->
\newpage
```{r, child="RECURSOS-INVESTIGACION/010-ANEXOS/010-ANEXOS.Rmd"}
```
