---
title: "Simulación sobre modelos entrenados"
output: pdf_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      out.width = '60%',
                      out.height = '60%',
                      fig.align = 'center',
                      message = FALSE)
```

<!-- LIBRERIAS -->
```{r, echo=FALSE}
library(fpp2)
```


## Modelo arima

```{r}
fit <- auto.arima(sunspotarea)

nSim <- 3L
h <- 20L

sim <- ts(matrix(0, nrow=h, ncol=nSim),
  start=end(sunspotarea)[1L]+1L)

for(i in seq(nSim)){
  sim[,i] <- simulate(fit, nsim=h)
}

autoplot(sunspotarea) + 
    autolayer(forecast(fit,h=h), series = 'proyeccion') +
    autolayer(sim)

```


\newpage
## Modelo redes neuronales

```{r}
fit <- nnetar(sunspotarea,lambda=0)

nSim <- 3L
h <- 20L

sim <- ts(matrix(0, nrow=h, ncol=nSim),
  start=end(sunspotarea)[1L]+1L)

for(i in seq(nSim)){
  sim[,i] <- simulate(fit, nsim=h)
}

autoplot(sunspotarea) + 
    autolayer(forecast(fit,h=h), series = 'proyeccion') +
    autolayer(sim)

```
