---
output: pdf_document
---

# Alcance y delimitación

El presente trabajo de investigación se circunscribirá al estudio de las entidades de intermediación de servicios financieras de Bolivia, definidas en el artículo 151 de la ley 393. Con fines de obtener la información que coadyuve a generar la determinación de pronósticos mediante redes neuronales, como herramienta en la toma de decisiones a nivel gerencial y la evaluación de las mismas.

Para viabilizar la realización del tema de investigación se ha elegido, que se tomará como modelo de análisis a las siguientes entidades:

- Bancos múltiples
- Bancos PYME
- Entidades financieras de vivienda 
- Cooperativas de ahorro y crédito abiertas
- Instituciones financieras de desarrollo
- Bancos de desarrollo productivo

para tener acceso a la información homogénea requerida y permita generalizar los resultados obtenidos de las gestiones de 2014 a 2022 y los cinco años proyectados de estas entidades que corresponden al ámbito delimitado. El tema elegido y propuesto, se realizará en un tiempo no mayor a diez meses, a partir de la aprobación y registro del plan de investigación presentado.


