---
output: pdf_document
---

<!-- Configuración CHUNKS -->
```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      fig.align='center',
                      out.height='60%',
                      out.width='100%')
```

```{r}
source('RECURSOS-INVESTIGACION/R/camel-get-datCamelIndicadores.R')
source('RECURSOS-INVESTIGACION/R/camel-get-limites-rangos.R')
source("RECURSOS-INVESTIGACION/R/camel-get-tabla-referencia-calificaciones.R")
source('RECURSOS-INVESTIGACION/R/camel-calificacion-indicadores.R')
source('RECURSOS-INVESTIGACION/R/camel-calificacion-entidad.R')
source('RECURSOS-INVESTIGACION/R/camel-getListStatsIndicadores.R')
source('RECURSOS-INVESTIGACION/R/camel-getListPlotsIndicadores.R')
source('RECURSOS-INVESTIGACION/R/camel-get-datIdsNamesCamelInds.R')
source("RECURSOS-INVESTIGACION/R/camel-render-tables-indicadoresStats.R")
source('RECURSOS-INVESTIGACION/R/camel-tendencia-stats-overview.R')
source('RECURSOS-INVESTIGACION/R/camel-plot-functions.R')
source("RECURSOS-INVESTIGACION/R/render-table-basic.R")

require(stringr)
require(ggplot2)
require(patchwork)
require(knitr)
require(kableExtra)
require(dplyr)

if (!('dat' %in% ls())) {dat <- NULL}

datCamelIndNorm <- getDatCamelIndicadores(dat=dat, by='TOTAL_SISTEMA')

datCamelRangosLimites <- getDatCamelRangosLimites(datCamelIndNorm)

datCamelCalificacionIndicadores <- 
    getDatCamelCalificacionIndicadores(datCamelIndNorm,datCamelRangosLimites)
datCamelCalificacionIndicadoresHard <- 
    getDatCamelCalificacionIndicadores(datCamelIndNorm,datCamelRangosLimites,
                                       calificacionDuro = TRUE)

datCamelCalificacionEntidadSinPoderar <- 
    getDatCamelCalificacionEntidad(datCamelCalificacionIndicadores, FALSE)
datCamelCalificacionEntidadSinPoderarHard <- 
    getDatCamelCalificacionEntidad(datCamelCalificacionIndicadoresHard, FALSE)

datCamelCalificacionEntidad <- 
    getDatCamelCalificacionEntidad(datCamelCalificacionIndicadores)
datCamelCalificacionEntidadHard <- 
    getDatCamelCalificacionEntidad(datCamelCalificacionIndicadoresHard)

### Otros

tableRefenceCamelCalificaciones <- getTableRefenceCamelCalificaciones()
datIdsNamesCamelInds <- getDatIdsNamesCamelIndicadores()

```

## Resultados CAMEL total sistema

### Resutados CAMEL con rangos flexibles sin ponderar

```{r}
ids <- c('C','A','M','E','L')
listResult <- getListStatsOverviewInd(ids, 
                                      datCamelCalificacionEntidadSinPoderar, 
                                      datIdsNamesCamelInds,
                                      TRUE)
listPlots <- getListPlotsInd(listResult, scaleOne = FALSE,numDigScale = 0.01)
listTablesRender <- renderListTablesInd(listResult, 'Tendencia y estadisticas C-A-M-E-L con rangos flexibles sin ponderar', 1)
```


```{r, fig.height = 20, fig.width = 20, fig.cap='Resultados C-A-M-E-L con rangos flexibles sin ponderar'}
wrap_plots(listPlots, ncol = 1)
```

```{r}
listTablesRender %>% 
    footnote(general_title = 'NOTA:',
                              general = 'Los sectores en la tabla fueron ordenados en función del más al menos favorable dado su indicador promedio.')
```

### Resutados CAMEL con rangos estrictos sin ponderar


```{r}
ids <- c('C','A','M','E','L')
listResult <- getListStatsOverviewInd(ids, 
                                      datCamelCalificacionEntidadSinPoderarHard, 
                                      datIdsNamesCamelInds,
                                      TRUE)
listPlots <- getListPlotsInd(listResult)
listTablesRender <- renderListTablesInd(listResult, 'Tendencia y estadisticas C-A-M-E-L con rangos estrictos sin ponderar', 1)
```

```{r, fig.height = 20, fig.width = 20, fig.cap='Resultados C-A-M-E-L con rangos extrictos sin ponderar'}
wrap_plots(listPlots, ncol = 1)
```

```{r}
listTablesRender %>% 
    footnote(general_title = 'NOTA:',
                              general = 'Los sectores en la tabla fueron ordenados en función del más al menos favorable dado su indicador promedio.')
```

\newpage
### Calificación CAMEL


```{r}
datAuxCAMEL <- 
    datCamelCalificacionEntidad %>% 
    select(ID,TIPO_DE_ENTIDAD,FECHA) %>% 
    mutate(CAMEL_FLEXIBLE=datCamelCalificacionEntidad$CAMEL,
           CAMEL_ESTRICTO=datCamelCalificacionEntidadHard$CAMEL)
```


```{r}
ids <- c('CAMEL_FLEXIBLE','CAMEL_ESTRICTO')
listResult <- getListStatsOverviewInd(ids, datAuxCAMEL, datIdsNamesCamelInds,TRUE)
listPlots <- getListPlotsInd(listResult)
listTablesRender <- renderListTablesInd(listResult, 'Tendencia y estadisticas CAMEL', 1)
```

```{r, fig.height = 20, fig.width = 20, fig.cap='Resultados CAMEL'}
wrap_plots(listPlots, ncol = 1)
```

```{r}
listTablesRender %>% 
    footnote(general_title = 'NOTA:',
                              general = 'Los sectores en la tabla fueron ordenados en función del más al menos favorable dado su indicador promedio.')
```

```{r}
renderTableBasic(tableRefenceCamelCalificaciones)
```
