---
output: pdf_document
---

# Estructura capitular tentativo

Agradecimiento
\newline Dedicatoria
\newline Resumen
\newline Abstract
\newline Índice de contenido
\newline Índice de tablas, gráficas, cuadros, etc.
\newline Introducción

\vspace{3.5mm}
**Capítulo I Antecedentes**
\vspace{3.5mm}

Históricos
\newline Legales
\newline Organizacionales
\newline Económicos y financieros
\newline Intermediación financiera
\newline Sociales

\vspace{3.5mm}
**Capítulo II Diagnóstico de las instituciones financieras del sistema financiero**
\vspace{3.5mm}

Globalización
\newline Mercados internacionales
\newline Organización e infraestructura de los mercados financieros
\newline Justificación e importancia
\newline Evaluación de la información económica, financiera
\newline Obtención de las conclusiones preliminares y sus soluciones

\vspace{3.5mm}
**Capítulo III Marco teórico**
\vspace{3.5mm}

Objetivo del sustento teórico
\newline Definición de términos financieros básicos
\newline Sistema financiero nacional e internacional
\newline Intermediación financiera y regulación financiera
\newline Valoración de acciones por método de flujos descontados
\newline Definición de acción sobrevalorada -subvalorada, y la toma de decisiones.

\vspace{3.5mm}
**Capítulo IV Determinación del valor de acciones de compañías por flujos descontados**
\vspace{3.5mm}

Diferencia entre capital de deuda y capital patrimonial
\newline Diferencia en precio y valor
\newline Valor del dinero en el tiempo
\newline Criterio de riesgo – rendimiento
\newline Determinación de flujos futuros
\newline Valor descontado de flujos de acciones
\newline Limitaciones de la valoración de acciones por flujos descontados

\vspace{3.5mm}
**Capítulo V Simulación de valoración de acciones por flujos descontados**
\vspace{3.5mm}

Planteamiento de supuestos

\vspace{3.5mm}
**Capítulo VI Conclusiones y recomendaciones**
\vspace{3.5mm}

Conclusiones
\newline Recomendaciones

\vspace{3.5mm}
**Bibliografía consultada**
\vspace{3.5mm}

\vspace{3.5mm}
**Anexos y apéndices**
\vspace{3.5mm}

\vspace{3.5mm}
**Glosario**
\vspace{3.5mm}