---
output: pdf_document
---

<!-- FUNCIONES NECESARIAS -->
```{r}
source('RECURSOS-INVESTIGACION/R/camel-get-datCamelIndicadores.R')
source('RECURSOS-INVESTIGACION/R/camel-render-table-datCamelIndNorm.R')

source('RECURSOS-INVESTIGACION/R/camel-get-limites-rangos.R')
source('RECURSOS-INVESTIGACION/R/camel-calificacion-indicadores.R')
source('RECURSOS-INVESTIGACION/R/camel-calificacion-entidad.R')
source('RECURSOS-INVESTIGACION/R/render-table-basic.R')

if (!('dat' %in% ls())) {dat <- NULL}

datCamelIndNorm <- getDatCamelIndicadores(dat=dat, by='TIPO_DE_ENTIDAD')
datCamelRangosLimites <- getDatCamelRangosLimites(datCamelIndNorm)

datCamelCalificacionIndicadores <-
    getDatCamelCalificacionIndicadores(datCamelIndNorm,datCamelRangosLimites)

datCamelCalificacionEntidad <- 
    getDatCamelCalificacionEntidad(datCamelCalificacionIndicadores)

#########################################################################

dateFilter <- '2022-01-01'

datCamelIndNorm <- datCamelIndNorm %>% filter(FECHA>dateFilter)

datCamelCalificacionIndicadores <- datCamelCalificacionIndicadores %>% filter(FECHA>dateFilter)
datCamelCalificacionEntidad <- datCamelCalificacionEntidad %>% filter(FECHA>dateFilter)

```


\subsection*{Anexo 3 - Indicadores CAMEL calculados}

\subsubsection*{Capital}

```{r}
id <- 'indCap'
renderTableCamelIndNorm(id, datCamelIndNorm, 'Indicadores de capital CAMEL') %>% 
    footnote(general = 'Las variables presentadas corresponden a los meses contenidos de la gestión 2022.',
             general_title = 'NOTA: ' )
```


\newpage
\subsubsection*{Activos}

```{r}
id <- 'indAct'
renderTableCamelIndNorm(id, datCamelIndNorm, 'Indicadores de activos CAMEL') %>% 
    footnote(general = 'Las variables presentadas corresponden a los meses contenidos de la gestión 2022.',
             general_title = 'NOTA: ' )
```


\newpage
\subsubsection*{Administración y rentabilidad}

```{r}
id1 <- 'indAdm'
id2 <- 'indBenf'
renderTableCamelIndNorm2(id1, id2 , datCamelIndNorm, 'Indicadores de administración y rentabilidad CAMEL') %>% 
    footnote(general = 'Las variables presentadas corresponden a los meses contenidos de la gestión 2022.',
             general_title = 'NOTA: ' )
```


\newpage
\subsubsection*{Liquidez}

```{r}
id <- 'indLq'
renderTableCamelIndNorm(id, datCamelIndNorm, 'Indicadores de liquidez CAMEL') %>% 
    footnote(general = 'Las variables presentadas corresponden a los meses contenidos de la gestión 2022.',
             general_title = 'NOTA: ' )
```


