
```{r}
# PAQUETES NECESARIOS
require(glue)
require(knitr)
require(kableExtra)
require(dplyr)

# FUNCIONES NECESARIAS
source('RECURSOS-INVESTIGACION/R/get-dat-basic-normalizada.R')
source("RECURSOS-INVESTIGACION/R/get-dat-basic.R")
source("RECURSOS-INVESTIGACION/R/get-dat-group.R")
source("RECURSOS-INVESTIGACION/R/def-mod-entidades.R")
source("RECURSOS-INVESTIGACION/R/render-table-basic.R")
source("RECURSOS-INVESTIGACION/R/handles.R")

# VARIABLES GLOBALES DEL CAPITULO
datBasic <- getDatEEFF()
dat <- getDatEEFFNormalizada(by='TIPO_DE_ENTIDAD')
entidadesCompModelo <- getEntidadesCompModelo(datBasic)
datGroupBySector <- getDatEEFFByGroup(datBasic,by = 'TIPO_DE_ENTIDAD' )
```

\subsection*{Anexo 6 - Entidades financieras comprendidas en el diagnostico financiero}


```{r}
idTipoEntidad <- 'BANCOS_MULTIPLES'

entidadesModelo <- 
    entidadesCompModelo %>% 
    filter(TIPO_DE_ENTIDAD==idTipoEntidad) %>%
    select(SIGLA,ENTIDAD,DE,HASTA)
```


```{r bancos-multiples-datos}
captionTable <- glue('{handle$toUpperFirstText(gsub("_"," ",idTipoEntidad))} contenidas en los datos')
renderTableBasic(entidadesModelo,captionTable = captionTable)
```


```{r}
idTipoEntidad <- 'BANCOS_PYME'
entidadesModelo <- 
    entidadesCompModelo %>% 
    filter(TIPO_DE_ENTIDAD==idTipoEntidad) %>%
    select(SIGLA,ENTIDAD,DE,HASTA)
```

```{r bancos-pyme-datos}
captionTable <- glue('{gsub("pyme","PYME",handle$toUpperFirstText(gsub("_"," ",idTipoEntidad)))} contenidos en los datos')
renderTableBasic(entidadesModelo,captionTable = captionTable)
```


```{r}
idTipoEntidad <- 'BANCOS_DE_DESARROLLO_PRODUCTIVO'
entidadesModelo <- 
    entidadesCompModelo %>% 
    filter(TIPO_DE_ENTIDAD==idTipoEntidad) %>%
    select(SIGLA,ENTIDAD,DE,HASTA)
```

```{r banco-desarrollo-productivo-datos}
captionTable <- glue('{handle$toUpperFirstText(gsub("_"," ",idTipoEntidad))} contenidas en los datos')
renderTableBasic(entidadesModelo,captionTable = captionTable)
```

\newpage

```{r}
idTipoEntidad <- 'INSTITUCIONES_FINANCIERAS_DE_DESARROLLO'
entidadesModelo <- 
    entidadesCompModelo %>% 
    filter(TIPO_DE_ENTIDAD==idTipoEntidad) %>%
    select(SIGLA,ENTIDAD,DE,HASTA)
```

```{r intituciones-financieras-desarrollo-datos}
captionTable <- glue('{handle$toUpperFirstText(gsub("_"," ",idTipoEntidad))} contenidas en los datos')
renderTableBasic(entidadesModelo,captionTable = captionTable)
```


```{r}
idTipoEntidad <- 'ENTIDADES_FINANCIERAS_DE_VIVIENDA'
entidadesModelo <- 
    entidadesCompModelo %>% 
    filter(TIPO_DE_ENTIDAD==idTipoEntidad) %>%
    select(SIGLA,ENTIDAD,DE,HASTA)
```

```{r entidades-financieras-vivienda-datos}
captionTable <- glue('{handle$toUpperFirstText(gsub("_"," ",idTipoEntidad))} contenidas en los datos')
renderTableBasic(entidadesModelo,captionTable = captionTable) %>% 
    footnote(general = 'NA indica que la razon social de la intitucion es deconocida',
             general_title = 'NOTA: ' )
```


```{r}
idTipoEntidad <- 'COOPERATIVAS_DE_AHORRO_Y_CREDITO'
entidadesModelo <- 
    entidadesCompModelo %>% 
    filter(TIPO_DE_ENTIDAD==idTipoEntidad) %>%
    select(SIGLA,ENTIDAD,DE,HASTA)
```

```{r cooperativas-datos}
captionTable <- glue('{handle$toUpperFirstText(gsub("_"," ",idTipoEntidad))} contenidas en los datos')
renderTableBasic(entidadesModelo,captionTable = captionTable)
```
