
<!-- FUNCIONES NECESARIAS -->
```{r}
source('RECURSOS-INVESTIGACION/R/camel-get-datCamelIndicadores.R')
source('RECURSOS-INVESTIGACION/R/camel-render-table-datCamelIndNorm.R')

source('RECURSOS-INVESTIGACION/R/camel-get-limites-rangos.R')
source('RECURSOS-INVESTIGACION/R/camel-calificacion-indicadores.R')
source('RECURSOS-INVESTIGACION/R/camel-calificacion-entidad.R')
source('RECURSOS-INVESTIGACION/R/render-table-basic.R')

if (!('dat' %in% ls())) {dat <- NULL}


datCamelIndNorm <- getDatCamelIndicadores(dat=dat, by='TIPO_DE_ENTIDAD')
datCamelRangosLimites <- getDatCamelRangosLimites(datCamelIndNorm)

datCamelCalificacionIndicadores <-
    getDatCamelCalificacionIndicadores(datCamelIndNorm,datCamelRangosLimites)

datCamelCalificacionEntidadSinPoderar <- 
    getDatCamelCalificacionEntidad(datCamelCalificacionIndicadores, FALSE)

datCamelCalificacionEntidad <- 
    getDatCamelCalificacionEntidad(datCamelCalificacionIndicadores)

#########################################################################

dateFilter <- '2022-01-01'

datCamelIndNorm <- datCamelIndNorm %>% filter(FECHA>dateFilter)

datCamelCalificacionIndicadores <- datCamelCalificacionIndicadores %>% filter(FECHA>dateFilter)
datCamelCalificacionEntidadSinPoderar <- datCamelCalificacionEntidadSinPoderar %>% filter(FECHA>dateFilter)
datCamelCalificacionEntidad <- datCamelCalificacionEntidad %>% filter(FECHA>dateFilter)

```


\subsection*{Anexo 8 - Calificaciones CAMEL}

\subsubsection*{Calificaciones CAMEL sin ponderar}

- Capital (C)
- Activos (A)
- Administración (M)
- Beneficios (E)
- Liquidez (L)

```{r}
datAux <- datCamelCalificacionEntidadSinPoderar[,c(-1,-9)]

datAux$TIPO_DE_ENTIDAD <- gsub('_',' ', datAux$TIPO_DE_ENTIDAD)
names(datAux) <- gsub('_',' ', names(datAux))

renderTableBasic(datAux, 'Calificaciones CAMEL sin poderar') %>% 
    footnote(general = 'Las variables presentadas corresponden a los meses contenidos de la gestión 2022.',
             general_title = 'NOTA: ' )
```



\newpage
\subsubsection*{Calificación CAMEL ponderada}

- Capital (C)
- Activos (A)
- Administración (M)
- Beneficios (E)
- Liquidez (L)

```{r}
datAux <- datCamelCalificacionEntidad[,-1]

datAux$TIPO_DE_ENTIDAD <- gsub('_',' ', datAux$TIPO_DE_ENTIDAD)
names(datAux) <- gsub('_',' ', names(datAux))

renderTableBasic(datAux, 'Calificación CAMEL ponderada') %>% 
    footnote(general = 'Las variables presentadas corresponden a los meses contenidos de la gestión 2022.',
             general_title = 'NOTA: ' )
```
