```{=latex}
\startcontents[anexosections]
```

<!-- ANEXOS -->
\newpage
\vspace*{\fill}
\section*{ANEXOS}
\thispagestyle{empty}
\vspace*{\fill}

```{=latex}
\newpage
\printcontents[anexosections]{}{1}{\section*{INDICE ANEXOS}}
```

<!-- ############################################################### -->
<!-- ###################### ANEXO 1 #################################-->
<!-- ############################################################### -->

\newpage
```{r, child="RECURSOS-INVESTIGACION/010-ANEXOS/010-01-SOLICITUD-ASFI.Rmd"}

```


<!-- ############################################################### -->
<!-- ###################### ANEXO 2 #################################-->
<!-- ############################################################### -->

\newpage
```{r, child="RECURSOS-INVESTIGACION/010-ANEXOS/010-02-RESPUESTA-ASFI.Rmd"}

```

<!-- ############################################################### -->
<!-- ###################### ANEXO 3 #################################-->
<!-- ############################################################### -->
\newpage
```{r, child="RECURSOS-INVESTIGACION/010-ANEXOS/010-03-ANTECEDENTES.Rmd"}

```

<!-- ############################################################### -->
<!-- ###################### ANEXO 4 #################################-->
<!-- ############################################################### -->
\newpage
```{r, child="RECURSOS-INVESTIGACION/010-ANEXOS/010-04-MCO.Rmd"}

```

<!-- ############################################################### -->
<!-- ###################### ANEXO 5 #################################-->
<!-- ############################################################### -->
\newpage
```{r, child="RECURSOS-INVESTIGACION/010-ANEXOS/010-05-KPSS.Rmd"}

```

<!-- ############################################################### -->
<!-- ###################### ANEXO 6 #################################-->
<!-- ############################################################### -->
\newpage
```{r, child="RECURSOS-INVESTIGACION/010-ANEXOS/010-06-BFGS.Rmd"}

```

<!-- ############################################################### -->
<!-- ###################### ANEXO 7 #################################-->
<!-- ############################################################### -->
\newpage
```{r, child="RECURSOS-INVESTIGACION/010-ANEXOS/010-07-AICC.Rmd"}

```

<!-- ############################################################### -->
<!-- ###################### ANEXO   #################################-->
<!-- ############################################################### -->
\newpage
```{r, child="RECURSOS-INVESTIGACION/010-ANEXOS/010-40-ENTIDADES-COMPRENDIDAS-DIAGNOSTICO.Rmd"}

```

<!-- ############################################################### -->
<!-- ###################### ANEXO   #################################-->
<!-- ############################################################### -->
\newpage
```{r, child="RECURSOS-INVESTIGACION/010-ANEXOS/010-45-PROYECIONES-MODELOS.Rmd"}

```

<!-- ############################################################### -->
<!-- ###################### ANEXO  #################################-->
<!-- ############################################################### -->

\newpage
```{r, child="RECURSOS-INVESTIGACION/010-ANEXOS/010-50-INDICADORES-CAMEL.Rmd"}

```

<!-- ############################################################### -->
<!-- ###################### ANEXO #################################-->
<!-- ############################################################### -->

\newpage
```{r, child="RECURSOS-INVESTIGACION/010-ANEXOS/010-60-CALIFICACION-CAMEL.Rmd"}

```


<!-- ############################################################### -->
<!-- ###################### ANEXO  #################################-->
<!-- ############################################################### -->

\newpage
```{r, child="RECURSOS-INVESTIGACION/010-ANEXOS/010-70-VARIABLES-CAMEL.Rmd"}

```

```{=latex}
\stopcontents[anexosections]
```