## Ponderación de elementos CAMEL

La ponderación de los elementos CAMEL son asignados siguiendo los lineamientos presentados en el marco teórico (Ver sección \@ref(MT-DEFINICION-PONDERACION-CAMEL)), dando mayor peso a los indicadores de capital y activos, seguido de los indicadores de beneficios y liquidez, dejando en último término los indicadores de administración.

\begin{equation}
CAMEL = \text{30\%C + 30\%A + 10\%M + 15\%E + 15\%L}
(\#eq:df-camel)
\end{equation}

Siendo consecuentes que la mayor ponderación está concentrado en los indicadores de capital y activos ya que en último termino son estos mismos con la que una institución financiera puede hacer frente a sus obligaciones con terceros, así también, dando mayor ponderación a los indicadores de rendimiento y liquidez respecto a los indicadores de administración siendo consecuente que la relación que guardan los mismos con el activo y el capital, donde el rendimiento tiene efectos sobre el capital y por el otro lado la liquidez tiene efectos sobre los activos.


