<!-- Configuración CHUNKS -->

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      fig.align='center',
                      out.height='60%',
                      out.width='100%')

setwd('../../../..')
knitr::opts_knit$set(root.dir = getwd())

options(scipen=999)

```

```{r}
source('RECURSOS-INVESTIGACION/R/camel-get-datCamelIndicadores.R')
source('RECURSOS-INVESTIGACION/R/camel-getListStatsIndicadores.R')
source('RECURSOS-INVESTIGACION/R/camel-getListPlotsIndicadores.R')
source('RECURSOS-INVESTIGACION/R/camel-get-datIdsNamesCamelInds.R')
source("RECURSOS-INVESTIGACION/R/camel-render-tables-indicadoresStats.R")
source("RECURSOS-INVESTIGACION/R/render-table-basic.R")
source("RECURSOS-INVESTIGACION/R/handles.R")

require(dplyr)
require(stringr)
require(glue)
require(ggplot2)
require(patchwork)
require(knitr)
require(kableExtra)

if (!('dat' %in% ls())) {dat <- NULL}

rootFile_datCamelIndNorm <- 'FUENTES-DE-DATOS/DATA/datCamelIndNorm_TipoDeEntidad.rds' 
if (file.exists(rootFile_datCamelIndNorm)){datCamelIndNorm <- readRDS(rootFile_datCamelIndNorm)}
if (!file.exists(rootFile_datCamelIndNorm)){datCamelIndNorm <- getDatCamelIndicadores(dat=dat, by='TIPO_DE_ENTIDAD')}

datIdsNamesCamelInds <- getDatIdsNamesCamelIndicadores()
```

<!-- ##################################################### -->
<!-- #####################  INDICADORES DE ACTIVOS         -->
<!-- ##################################################### -->

```{r df-indicadores-activos-tabla}
ids <- c('indAct_CEC','indAct_CPC','indAct_CPCM','indAct_CRC')
listResult <- getListStatsOverviewInd(ids, datCamelIndNorm, datIdsNamesCamelInds)
listPlots <- getListPlotsInd(listResult)
listTablesRender <- renderListTablesInd(listResult, 'Tendencia y estadísticas de indicadores de activos', 6)

```

```{r, fig.height = 20, fig.width = 20, fig.cap=''}
wrap_plots(listPlots, ncol = 1)
```


```{r}
listTablesRender
```


