<!-- Configuración CHUNKS -->

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      fig.align='center',
                      out.height='60%',
                      out.width='100%')

setwd('../../../..')
knitr::opts_knit$set(root.dir = getwd())

options(scipen=999)

```

```{r}
source('RECURSOS-INVESTIGACION/R/get-dat-basic-normalizada.R')
source('RECURSOS-INVESTIGACION/R/pef-r2-ids-eeff-forecast.R')
source('RECURSOS-INVESTIGACION/R/pef-list-summary-resumen.R')
source('RECURSOS-INVESTIGACION/R/pef-get-dats-for-forescat.R')
source('RECURSOS-INVESTIGACION/R/pef-get-ids-for-models.R')
source("RECURSOS-INVESTIGACION/R/pef-get-camel-test.R")
source("RECURSOS-INVESTIGACION/R/pef-aux-render-table.R")
source("RECURSOS-INVESTIGACION/R/render-table-basic.R")

require(kableExtra)
require(patchwork)
require(ggplot2)
require(dplyr)
require(fpp2)

if (!('listResultPEF' %in% ls())) {
    
    rootFile_datTotalSistema <- 'FUENTES-DE-DATOS/DATA/datTotalSistema.rds' 
    if (file.exists(rootFile_datTotalSistema)){datTotalSistema <- readRDS(rootFile_datTotalSistema)}
    if (!file.exists(rootFile_datTotalSistema)){datTotalSistema <- getDatEEFFNormalizada(by = 'TOTAL_SISTEMA')}
    
    ids <- getVariablesForModelsForecast()
    
    if (!file.exists('FUENTES-DE-DATOS/DATA/listResultPEF.rds')) {
        listResultPEF <- getListFittedAndSimulateModels(datTotalSistema,ids)
    }else{
        listResultPEF <- readRDS(file ='FUENTES-DE-DATOS/DATA/listResultPEF.rds')
    }
    
    listResumeModels <- getListResumeSummaryModels(listResultPEF)
    listDatsForTestCamels <- getDatsForTestCamels(listResultPEF,datTotalSistema,12,TRUE)
    
    originalCamelTest <- getCamelTestForecast(listDatsForTestCamels$datCuentas)
    nnCamelTest <- getCamelTestForecast(listDatsForTestCamels$nnDataForecastCuentas)
    mcoCamelTest <- getCamelTestForecast(listDatsForTestCamels$mcoDataForecastCuentas)
    arimaCamelTest <- getCamelTestForecast(listDatsForTestCamels$arimaDataForecastCuentas)
    
    camelTestModels <- bind_rows(originalCamelTest,
                                 nnCamelTest,
                                 mcoCamelTest,
                                 arimaCamelTest)
    
    id <- 'EERR_S2_RESULTADO_NETO_DE_LA_GESTION'
    
    trendCamelRNN <- readRDS(file ='FUENTES-DE-DATOS/DATA/trendCamelRNN.rds')
    sdCamelRNN <- readRDS(file ='FUENTES-DE-DATOS/DATA/sdCamelRNN.rds')
}

```

<div style="text-align: center;">

<br><br>

### EFICIENCIA DE LOS MODELOS EN EL ENTRENAMIENTO

```{r}
listResumeModels$r2ModelsResum %>% 
    filter(CUENTAS==id) %>% 
    transformTableAuxPef %>% 
    kable()  %>%
    kable_styling(bootstrap_options = "striped", full_width = FALSE, position="center")
                  
```


### EFICIENCIA DE LOS MODELOS EN LOS PRONOSTICOS

```{r}
listResumeModels$r2ForecastResum %>% 
    filter(CUENTAS==id) %>% 
    transformTableAuxPef %>% 
    kable()  %>%
    kable_styling(bootstrap_options = "striped", full_width = FALSE, position="center")
```


<br><br><br><br><br>

```{r, fig.cap=''}
autoplot(listResultPEF[[id]]$tsDatTrain, 
         main = '', 
         ylab='RESULTADO NETO DE LA GESTION', 
         xlab='', 
         series='DATOS DE ENTENAMIENTO') +
    autolayer(listResultPEF[[id]]$tsDatTest, 
         main = '', 
         ylab='RESULTADO NETO DE LA GESTION', 
         xlab='', 
         series='DATOS DE PRUEBAS') +
    autolayer(forecast(listResultPEF[[id]]$mcoModel, h = 12), 
         PI = FALSE, 
         main='', 
         ylab='RESULTADO NETO DE LA GESTION', 
         xlab='', 
         series='MCO') + 
    autolayer(forecast(listResultPEF[[id]]$arimaModel, h = 12), 
         PI = FALSE, 
         main='', 
         ylab='RESULTADO NETO DE LA GESTION', 
         xlab='', 
         series='ARIMA') +
    autolayer(forecast(listResultPEF[[id]]$nnModel, h = 12), 
         PI = FALSE, 
         main='', 
         ylab='RESULTADO NETO DE LA GESTION', 
         xlab='', 
         series='NN')
```

</div>