getVariablesForModelsForecast <- function() {
    ids <- c('ACTIVO',
             
             'COEFICIENTE_DE_ADECUACION_PATRIMONIAL',
             
             'ACTIVO_CARTERA_CARTERA_VENCIDA_TOTAL',
             'ACTIVO_CARTERA_CARTERA_VENCIDA',
             'ACTIVO_CARTERA_CARTERA_REPROGRAMADA_VENCIDA',
             'ACTIVO_CARTERA_CARTERA_REESTRUCTURADA_VENCIDA',
             'ACTIVO_CARTERA_CARTERA_REPROGRAMADA_O_REESTRUCTURADA_VENCIDA',
             
             'ACTIVO_CARTERA_CARTERA_EJECUCION_TOTAL',
             'ACTIVO_CARTERA_CARTERA_EN_EJECUCION',
             'ACTIVO_CARTERA_CARTERA_REPROGRAMADA_EJECUCION',
             'ACTIVO_CARTERA_CARTERA_REESTRUCTURADA_EN_EJECUCION',
             'ACTIVO_CARTERA_CARTERA_REPROGRAMADA_O_REESTRUCTURADA_EN_EJECUCION',
             
             'ACTIVO_CARTERA_CARTERA_VIGENTE_TOTAL',
             'ACTIVO_CARTERA_CARTERA_VIGENTE',
             'ACTIVO_CARTERA_CARTERA_REPROGRAMADA_VIGENTE',
             'ACTIVO_CARTERA_CARTERA_REESTRUCTURADA_VIGENTE',
             'ACTIVO_CARTERA_CARTERA_REPROGRAMADA_O_REESTRUCTURADA_VIGENTE',
             
             'ACTIVO_CARTERA_PREVISION_PARA_INCOBRABILIDAD_DE_CARTERA',
             
             'PATRIMONIO',
             
             'ACTIVO_BIENES_REALIZABLES',
             
             'CUENTAS_CONTINGENTES_DEUDORAS',
             
             'EERR_S2_GASTOS_DE_ADMINISTRACION',
             
             'EERR_S2_IMPUESTOS',
             
             'RESULTADO_DE_OPERACION_BRUTO',
             
             'EERR_S2_RESULTADO_NETO_DE_LA_GESTION',
             
             'ACTIVO_DISPONIBILIDADES',
             
             'ACTIVO_INVERSIONES_TEMPORARIAS',
             
             'PASIVO')
    
    return(ids)
}