source("RECURSOS-INVESTIGACION\\R\\get-dat-basic.R")

dat <- getDatEEFF()

# TIPOS DE ENTIDADES
unique(dat$TIPO_DE_ENTIDAD)

# BANCOS_MULTIPLES
unique(dat[dat$TIPO_DE_ENTIDAD=='BANCOS_MULTIPLES','ENTIDIDAD'])
length(unique(dat[dat$TIPO_DE_ENTIDAD=='BANCOS_MULTIPLES','ENTIDIDAD']))

# BANCOS_PYME
unique(dat[dat$TIPO_DE_ENTIDAD=='BANCOS_PYME','ENTIDIDAD'])
length(unique(dat[dat$TIPO_DE_ENTIDAD=='BANCOS_PYME','ENTIDIDAD']))

# BANCOS_DE_DESARROLLO_PRODUCTIVO
unique(dat[dat$TIPO_DE_ENTIDAD=='BANCOS_DE_DESARROLLO_PRODUCTIVO','ENTIDIDAD'])
length(unique(dat[dat$TIPO_DE_ENTIDAD=='BANCOS_DE_DESARROLLO_PRODUCTIVO','ENTIDIDAD']))

# INSTITUCIONES_FINANCIERAS_DE_DESARROLLO
unique(dat[dat$TIPO_DE_ENTIDAD=='INSTITUCIONES_FINANCIERAS_DE_DESARROLLO','ENTIDIDAD'])
length(unique(dat[dat$TIPO_DE_ENTIDAD=='INSTITUCIONES_FINANCIERAS_DE_DESARROLLO','ENTIDIDAD']))

# ENTIDADES_FINANCIERAS_DE_VIVIENDA
unique(dat[dat$TIPO_DE_ENTIDAD=='ENTIDADES_FINANCIERAS_DE_VIVIENDA','ENTIDIDAD'])
length(unique(dat[dat$TIPO_DE_ENTIDAD=='ENTIDADES_FINANCIERAS_DE_VIVIENDA','ENTIDIDAD']))

# COOPERATIVAS_DE_AHORRO_Y_CREDITO
unique(dat[dat$TIPO_DE_ENTIDAD=='COOPERATIVAS_DE_AHORRO_Y_CREDITO','ENTIDIDAD'])
length(unique(dat[dat$TIPO_DE_ENTIDAD=='COOPERATIVAS_DE_AHORRO_Y_CREDITO','ENTIDIDAD']))

View(dat[dat$ENTIDIDAD=='VPT',])
